### ISSUE TITLE
Runtime error CALL_FUNCTION_CONFLICT_TYPE Except. CX_SY_DYN_CALL_ILLEGAL_TYPE

### ISSUE THREAD

**Issue by dimi309** [vlutsas/DST#1]
Great tool! Thanks so much for publishing it. VERY useful! I would like to report an error I have encountered while running it on a system with SAP_BASIS release 756.

The error produced is runtime error CALL_FUNCTION_CONFLICT_TYPE Except. CX_SY_DYN_CALL_ILLEGAL_TYPE near line 1520 of include "ZCF_DST_CLS":

`CALL FUNCTION 'POINT_IN_TIME_CONVERT'`

I have corrected it in my local installation. It is just that the data "guessed" by SAP a bit higher up:

`DATA(lv_duration_sec_int4) = CONV int4( lv_duration_secs ).`

... does not match the subsequently called POINT_IN_TIME_CONVERT function expects, to which it is passed as a parameter. It suffices to declare the datatype explicitly. I will introduce a pull request in case you are interested 😄

**Comment by vlutsas** [comment]
I didn't have an opportunity to check DST on 7.56, so glad it works on it,
for the exception of the fix you did. Thanks!

Best regards
Vladimir

**Comment by dimi309** [comment]
With pleasure! I hope the pull request helps 😄
